### ISSUE TITLE
Super Bagman does not download

### ISSUE THREAD

**Issue by RevQuixo** [MAME-GETTER/MiSTer_MAME_SCRIPTS#3]
Did a clean install deleting all files and once repopulated there is no sbagman.zip.  Launching the MRA indicated that r3,bin is missing for the game, so if this is a merged set with bagman.zip (not sure) there is at the very least a file missing.

**Comment by MAME-GETTER** [comment]
I will look in to this.

**Comment by MAME-GETTER** [comment]
RevQuixo I just made a change to the MAME-getter script can you run it again and see if you get sbagman.zip

**Comment by MAME-GETTER** [comment]
The sbagman MRA uses single quotes around the zip file in the MRA
`<rom index='0' md5='fa8e135d43bfafab71a3b608d825072b' type='merged|nonmerged|split' zip='sbagman.zip'>`


This is fixed with:

```
find "${MRADIR}" -name \*.mra | sort | while read i
do

  echo "${i}" > /tmp/mame.getter.mra.file

#find double quotes zip names
grep ".zip=" "${i}" | sed 's/.*\(zip=".*\)\.zip.*/\1/' | awk -F '"' '{print$2".zip"}' | sed s/\|/\\n/g | sort -u | grep -v ^.zip > /tmp/mame.getter.zip.file

#find sigle quotes zip names
grep ".zip=" "${i}" | sed -n 's/^.*'\''\([^'\'']*\)'\''.*$/\1/p'| sed s/\|/\\n/g | sort -u | grep -v ^.zip > /tmp/mame.getter.zip.file2

#put both files togther
cat /tmp/mame.getter.zip.file >> /tmp/mame.getter.zip.file2

sort -u /tmp/mame.getter.zip.file2 > /tmp/mame.getter.zip.file

rm /tmp/mame.getter.zip.file2

```

Waiting for others to confirm.... likely closing soon.

**Comment by RevQuixo** [comment]
Ran the script again and this time it pulled in arkanoid, berserk, and super bagman.  All good!

**Comment by MAME-GETTER** [comment]
Thank you for confirming. Closing
