### ISSUE TITLE
Could you please rename ROMDIR?

### ISSUE THREAD

**Issue by theypsilon** [MAME-GETTER/MiSTer_MAME_SCRIPTS#8]
Right now, mame-getter and hbmame-getter share same variable name 'ROMDIR' for two different paths (hbmame and mame).

That's no problem at all if the user uses the default options, or if configures them through **different** .ini files.

And certainly that's still the case when used in update_all.sh

But there, since I give the option of modifying .ini paths in update_all.ini, it would be interesting to give the possibility for using a **single** .ini file for all the scripts.

In fact, it is possible to do that right now. But since you can only define ROMDIR once, and you need to have 2 paths, 1 for mame and 2 for hbmame, it doesn't work well.

I propose to change the ROMDIR name to ROMMAMEDIR (or ROMDIRMAME) in mame-getter and ROMHBMAMEDIR (or ROMDIRHBMAME) in hbmame-getter.

For backwards compatibility, ROMDIR .ini variable could still get readed by the script. But would remain undocumented and deprecated.

**Comment by MAME-GETTER** [comment]
@theypsilon if you make a PR I will Merge, please ensure backward compatibility.
