### ISSUE TITLE
Problem with "" in .ini options

### ISSUE THREAD

**Issue by theypsilon** [MAME-GETTER/MiSTer_MAME_SCRIPTS#9]
Some people are trying to define ROMDIR like this:

ROMDIR="/media/fat/games/mame"

And that doesn't work with the current grep code. Without "" is fine.

I can take care of this one when I find the moment.

Writting it down to not forget about it.

**Comment by MAME-GETTER** [comment]
@theypsilon Make a PR and I will merge.
